version: '3.8'

services:
  database:
    image: postgres:16
    restart: unless-stopped
    shm_size: 1g
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - 15433:80
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - postgres-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin/

  scraper:
    build: ./schedule_scrape
    container_name: football_scraper
    restart: always
    networks:
      - postgres-network
    depends_on:
      - database

networks: 
  postgres-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  pgadmin-data:
    driver: local
